create external table s1200_dehumidifier (
    plc_alert_1 string,
    plc_alert_2 string,
    plc_alert_3 string,
    plc_alert_4 string,
    plc_alert_5 string,
    plc_alert_6 string,
    plc_alert_7 string,
    plc_alert_8 string,
    plc_alert_9 string,
    plc_alert_10 string,
    plc_alert_11 string,
    plc_alert_12 string,
    plc_alert_13 string,
    plc_alert_14 string,
    plc_alert_15 string,
    plc_alert_16 string,
    plc_alert_17 string,
    plc_alert_18 string,
    regenerative_electric_heating_fault string,
    regenerative_electric_heating_1_operation_feedback string,
    front_electric_heating_fault string,
    back_electric_heating_fault string,
    front_electric_heating_alarm string,
    back_electric_heating_alarm string,
    inlet_pressure_difference_1_alarm string,
    inlet_pressure_difference_2_alarm string,
    handle_pressure_difference_alarm string,
    regenerative_pressure_difference_alarm string,
    chiller_operation_signal string,
    unit_operation_1 string,
    unit_fault string,
    temperature_setpoint string,
    humidity_setpoint string,
    supply_air_temperature_actual_value string,
    return_air_humidity_actual_value string,
    fresh_air_temperature string,
    pre_cooling_supply_air_temperature string,
    post_cooling_supply_PID_output_percentage string,
    E1_supply_air_humidity string,
    E1_supply_air_temperature string,
    E2_return_air_humidity string,
    E2_return_air_temperature string,
    regeneration_PID_output_percentage string,
    regeneration_temperature string,
    regeneration_supply_air_temperature string,
    regeneration_overheating_alarm_setting_1 string,
    differential_pressure_pressure_setting string,
    inlet_differential_pressure_pressure_setting string,
    winding_overheating_alarm_setting string,
    a_phase_voltage string,
    b_phase_voltage string,
    c_phase_voltage string,
    a_phase_current string,
    b_phase_current string,
    c_phase_current string,
    a_b_phase_voltage string,
    b_c_phase_voltage string,
    a_c_phase_voltage string,
    energy_value string,


    rtd_timestamp string
)
partitioned by (rtd_date string, rtd_hour string, rtd_line string, rtd_name string)
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
location '/zec_data/s1200_dehumidifier';