input {
    rabbitmq {
        host => "10.10.16.128"
        port => 5672
        user => "test"
        password => "test"
        queue => "DCS_YL_GATHER_2_ES"
        exchange => "DCS_DATA_YL_2"
        vhost => "ZEC_SCADA"
        durable => true
		auto_delete => false
        prefetch_count => 8
        codec => plain
    }
}

filter {
	json {
		source => "message"
		target => "message"
	}
	
	date {
		match => ["[message][timestamp]", "UNIX"]
		target => "[message][timestamp]"		
	}
	mutate{
		add_field=>{
			# 'output_prefix'=>'/zec_data/'
			# 'ruby_rtd_index'=>0
		}
	}
	
	
	ruby{
		code=> "event.set('[message][timestamp_plus]', LogStash::Timestamp.at(event.get('[message][timestamp]').time.localtime + 8*60*60))"
	}

	
	grok{
		match=>{
			"[message][timestamp_plus]"=>"(?<rtd_date>\d{4}-\d{2}-\d{2})T(?<rtd_time>(?<rtd_hour>\d{2}):\d{2}:\d{2})\.\d{3}Z"
		}
		
		add_field => {
			"[message][rtd_date_time]" => "%{rtd_date} %{rtd_time}"
		}
	}

	ruby {
		code => '
			event.get("[message][data]").each{ |k, v|
				full_name="#{k}"
				name = full_name.split("_")[0]

				# index = Integer(event.get("ruby_rtd_index"))
				case name
				when "DB2004-00", "DB2015-27", "DB2016-28", "DB2017-29", "DB2018-00", "DB2008-24", "DB2009-25", "DB2010-26", "DB2011-00", "DB2019-21", "DB2020-22", "DB2021-23"
					rtd_index = "weighbrige"
				when "YFJD-ABE-2006", "YFJD-ABE-2007", "YFJD-ABE-2002", "YFJD-ABE-2001", "YFJD-ABE-2003", "YFJD-ABE-2004", "YFJD-ABE-2008", "YFJD-ABE-2009", "YFJP-ACB-2010"
					# platform_scale
					rtd_index = "weighbrige" 
				else
					rtd_index = ""
				end

				line = full_name.split("_")[1]

				event.set("[message][data][#{k}][rtd_timestamp]", event.get("[message][rtd_date_time]"))
				event.set("[message][data][#{k}][rtd_name]", name)
				event.set("[message][data][#{k}][rtd_line]", line)
				event.set("[message][data][#{k}][rtd_index]", rtd_index)
				event.set("[message][data][#{k}][rtd_date]", event.get("rtd_date"))
				event.set("[message][data][#{k}][rtd_hour]", event.get("rtd_hour"))
				event.set("[message][data][#{k}][rtd_time]", event.get("rtd_time"))
				event.set("[message][data][#{k}][rtd_type]", event.get("[message][type]"))
				# event.set("[message][data][#{k}][ruby_rtd_index]", event.get("ruby_rtd_index"))
				# event.set("[message][msg][#{index}]", event.get("[message][data][#{k}]"))
				# event.set("ruby_rtd_index", Integer(Integer(event.get("ruby_rtd_index"))+1).to_s)
			}
			event.set("message", event.get("[message][data]").values)
		'
		# remove_field => [ "[message][data]" ]
	}

	split {
		field => "message"
		# add_field => { "rtd_index" => "%{[message][rtd_index]}"}
		# remove_field => [ "[message][rtd_index]"]
	}

	mutate {
		# replace => { "message" => "%{message}"}
		remove_field => [ "event"]
	}
}


output {
	# stdout {
	# 	codec => rubydebug{
	# 		# format=>"%{[message][msg]}"
	# 	}
	# }
	if [message][rtd_index] == "air_compressor" {
		elasticsearch {
			hosts => ["http://10.10.16.111:9200", "http://10.10.16.112:9200"]
			index => "zec_yl_data_%{[message][rtd_index]}"
			action => "update"
			doc_as_upsert => true
			document_id => "%{[message][rtd_name]}"
			# document => "%{[@metadata][message]}"
			# script => "ctx._source.message = params.event.get('message')"
			codec=>plain{ 
				format=>"%{message}"
				# format=>"%{[message][data][G2101_L]}"
			}
			# template => "config/template/rabbitmq-to-es.json"
			# manage_template => "true"
			# template_overwrite => "true"
			# template_name => "zec_data_air_compressor"
		}

	}
	else {
		elasticsearch {
			hosts => ["http://10.10.16.111:9200", "http://10.10.16.112:9200"]
			index => "zec_yl_data_%{[message][rtd_index]}"
			action => "update"
			doc_as_upsert => true
			document_id => "%{[message][rtd_name]}"
			# document => "%{[@metadata][message]}"
			# script => "ctx._source.message = params.event.get('message')"
			codec=>plain{ 
				format=>"%{message}"
				# format=>"%{[message][data][G2101_L]}"
			}
		}

	}
}
