DROP TABLE IF EXISTS yl_coulter_mixer;
create external table yl_coulter_mixer(
host_mixing_frequency string,
host_feeding_frequency string,
host_discharge_frequency string,
host_actual_frequency string,
host_current_current string,
fly_cutter_1_set_frequency string,
fly_cutter_1_current_frequency string,
fly_cutter_1_current_current string,
fly_cutter_2_set_frequency string,
fly_cutter_2_current_frequency string,
fly_cutter_2_current_current string,
fly_cutter_3_set_frequency string,
fly_cutter_3_current_frequency string,
fly_cutter_3_current_current string,
fly_cutter_4_set_frequency string,
fly_cutter_4_current_frequency string,
fly_cutter_4_current_current string,
mixing_time_set_hours string,
mixing_time_set_minutes string,
mixing_time_set_seconds string,
host_inverter_fault string,
fly_cutter_1_inverter_fault string,
fly_cutter_2_inverter_fault string,
fly_cutter_3_inverter_fault string,
fly_cutter_4_inverter_fault string,
emergency_stop string,
discharge_valve_not_in_place string,
discharge_valve_not_closed string,
host_overload string,
fly_cutter_1_overload string,
fly_cutter_2_overload string,
fly_cutter_3_overload string,
fly_cutter_4_overload string,
host_fan_overload string,
low_air_pressure string,
safety_door_key_not_detected string,
discharge_valve_not_closed1 string,
inverter_fault string,
overload_alarm string,
manual_mode_light string,
automatic_mode_light string,
feeding string,
mixing string,
discharging string,
host_forward string,
fly_cutter_1_forward string,
fly_cutter_2_forward string,
fly_cutter_3_forward string,
fly_cutter_4_forward string,
host_fan_start string,
discharge_valve_open string,
discharge_valve_close string,
purge_valve_open string,
main_air_source string,
feeding_valve string,
pulse_dust_collector_open string,
host_inverter_fault_1 string,
host_frequency_reached string,
fly_cutter_1_inverter_fault_1 string,
fly_cutter_1_frequency_reached string,
fly_cutter_2_inverter_fault_1 string,
fly_cutter_2_frequency_reached string,
fly_cutter_3_inverter_fault_1 string,
fly_cutter_3_frequency_reached string,
fly_cutter_4_inverter_fault_1 string,
fly_cutter_4_frequency_reached string


)
partitioned by (rtd_date string, rtd_hour string, rtd_line string, rtd_name string)
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
location '/zec_data_yl/coulter_mixer';