DROP TABLE IF EXISTS yl_iron_remover;
create external table yl_iron_remover(
total_power string,
power_factor string,
current_electric string,
current_temperature string,
current_voltage string,
ab_line_voltage string,
bc_line_voltage string,
ac_line_voltage string,
phase_a_current string,
phase_b_current string,
phase_c_current string,
excitation_current_setting string,
actual_excitation_current string,
magnetic_field_intensity_ratio string,
magnetic_field_intensity string,
shutdown_delay_stop_oil_pump_setting string,
shutdown_discharge_delay_setting string,
shutdown_feed_valve_open_time_setting string,
shutdown_discharge_time_setting string,
shutdown_feed_valve_close_delay_setting string,
filtration_time_setting string,
discharge_time_setting_1 string,
feed_valve_open_delay_setting string,
discharge_time_setting string,
feed_valve_close_delay_setting string,
vibration_discharge_input_frequency string,
inverter_input_frequency_upper_limit string,
low_oil_flow_1 string,
oil_pump_fault_alarm string,
low_water_flow_alarm string,
abnormal_magnetic_field_alarm string,
regulator_fault_alarm string,
high_oil_temperature_alarm string,
oil_pump_fault string,
feed_valve_abnormal_working_position_alarm string,
feed_valve_abnormal_except_dust_position_alarm string,
vibration_motor_fault_alarm string,
rectifier_module_temperature_abnormal_alarm string,
vibration_motor_inverter_fault string,
emergency_stop_button_1 string,
low_water_flow string,
low_oil_flow string,
magnetization_operation string,
low_current string,
high_oil_temperature string,
working_position string,
except_dust_position string,
manual_mode_switch string,
auto_mode_switch string,
auto_start_button string,
auto_stop_button string,
local_mode_switch string,
remote_mode_switch string,
emergency_stop_button string,
blow_button string,
remote_start_signal string,
remote_stop_signal string,
system_auto_run string,
auto_run_stop string,
magnetization_drive string,
oil_pump_run string,
vibration_run string,
feeding_run string,
feed_valve_run string,
alarm string,
auto_run string,
blow_q string,
ultrasonic_run string


)
partitioned by (rtd_date string, rtd_hour string, rtd_line string, rtd_name string)
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
location '/zec_data_yl/iron_remover';